# -*- coding: utf-8 -*-
"""Deep Learning 1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/15qNtMJSbikaqYKkSQydQ9Qs2b8rj781W
"""

from flask import Flask

app = Flask(__name__)

@app.route('/')
def hello_world():
    return "Hello, World!"

if __name__ == '__main__':
  app.run(debug=True)